-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/Rvim/Rvim/blob/main/lua/rvim/config/options.lua
-- Add any additional options here
